apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/ksatyajitqwas/deployment-end-to-end.git
    targetRevision: HEAD
    path: project1-gitops-eks-platform/k8s/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
